apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: data-grid-operator
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  generators:
  - list:
      elements:
      - cluster: in-cluster
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "20"
      name: "{{cluster}}-data-grid-operator"
    spec:
      destination:
        name: "{{cluster}}"
        namespace: data-grid-operator
      project: default
      source:
        directory:
          jsonnet: {}
          recurse: true
        path: data-grid-operator
        repoURL: http://gitea.infra.svc.cluster.local:3000/demo/coolstore.git
        targetRevision: HEAD
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated: {}
        retry:
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m0s
          limit: 100