#!/bin/bash -e
# Set up huge pages
# Skips configuring Submainer gateways

TMPDIR=/tmp/configurehugepages

cd `dirname $0`
BASE=`pwd`
cd - >> /dev/null

source ${BASE}/../config.sh
source ${BASE}/generate-kubeconfigs

generate_kubeconfigs $TMPDIR


# label nodes
for clustername in ${CLUSTER_NAMES[@]}; do
  cmd="oc --insecure-skip-tls-verify --kubeconfig=${TMPDIR}/${clustername}"
  echo "adding labels to nodes in ${clustername}..."
  for w in $($cmd get node -oname -l node-role.kubernetes.io/worker=); do
    # Exclude any submariner gateway nodes
    $cmd get $w --show-labels | grep -q submariner.io/gateway=true && continue

    $cmd label $w node-role.kubernetes.io/worker-hp=
  done

  $cmd create -f ${BASE}/../yaml/hugepages/ || true
done


# wait for mcp
for clustername in ${CLUSTER_NAMES[@]}; do
  cmd="oc --insecure-skip-tls-verify --kubeconfig=${TMPDIR}/${clustername}"
  echo -n "waiting for worker-hp MCP on $clustername to be ready..."
  while ! $cmd get mcp worker-hp -o jsonpath="{.status.conditions[?(@.type=='Updating')].status}" | grep False > /dev/null; do
    echo -n "."
    sleep 30
  done
  echo "done"
done


#echo
#echo -n Verifying huge pages [this can take some time] ...
#while ! scripts/verify-hugepages >/dev/null 2>&1
#do
#	echo -n .
#	sleep 5
#done

rm -rf $TMPDIR
