#!/bin/bash

cd `dirname $0`
BASE=`pwd`
cd - >> /dev/null

# assign cluster-admin to argocd controller - this is so we can create the openshift-serverless namespace
oc apply -f ${BASE}/../yaml/argocd/argocd-cluster-admin-role-binding.yaml

echo -n "waiting for Application API to show up..."
until oc get crd/applications.argoproj.io >/dev/null 2>/dev/null; do
  echo -n "."
  sleep 10
done
echo "done"

echo -n "waiting for default AppProject to show up..."
until oc get -n openshift-gitops appproject/default >/dev/null 2>/dev/null; do
  echo -n "."
  sleep 10
done
echo "done"

oc apply -f ${BASE}/../yaml/argocd/coolstore.yaml
