#!/bin/bash

TMPDIR=/tmp/deletehugepages

cd `dirname $0`
BASE=`pwd`
cd - >> /dev/null

source ${BASE}/../config.sh

# setup kubeconfig files for each cluster
rm -rf $TMPDIR
mkdir -p $TMPDIR
for clustername in ${CLUSTER_NAMES[@]}; do
  config="$(oc get -n $clustername secrets -l hive.openshift.io/secret-type=kubeconfig -o jsonpath='{.items[0].data.kubeconfig}' 2>/dev/null)"
  if [ -z "$config" ]; then
    echo "could not retrieve kubeconfig for $clustername"
    exit 1
  fi
  echo -n "$config" | base64 -d > ${TMPDIR}/${clustername}
done


# unlabel nodes
for clustername in ${CLUSTER_NAMES[@]}; do
  cmd="oc --insecure-skip-tls-verify --kubeconfig=${TMPDIR}/${clustername}"
  echo "removing labels from nodes in ${clustername}..."
  for w in $($cmd get node -oname -l node-role.kubernetes.io/worker=); do
    # Exclude any submariner gateway nodes
    $cmd get $w --show-labels | grep -q submariner.io/gateway=true && continue

    $cmd label $w node-role.kubernetes.io/worker-hp-
  done
done


# wait for mcp
for clustername in ${CLUSTER_NAMES[@]}; do
  cmd="oc --insecure-skip-tls-verify --kubeconfig=${TMPDIR}/${clustername}"
  echo -n "waiting for worker-hp MCP on $clustername to be ready..."
  while ! $cmd get mcp worker-hp -o jsonpath="{.status.conditions[?(@.type=='Updating')].status}" | grep False > /dev/null; do
    echo -n "."
    sleep 30
  done
  echo "done"
done

rm -rf $TMPDIR
