#!/bin/bash

TMPDIR=/tmp/generateorders

cd $(dirname $0)
BASE=$(pwd)
cd - >> /dev/null

source ${BASE}/../config.sh

cmd="oc"

function get_kafka() {
  $cmd get -n $PROJ deploy/kafka-0 -o name 2>/dev/null
}

# check if we have everything deployed on the connected cluster (single
# cluster install)
KAFKA="$(get_kafka)"

if [ -z "$KAFKA" ]; then
  echo "kafka is not on the connected cluster - trying to see if we can connect to coolstore-a"

  # setup kubeconfig for coolstore-a
  rm -rf $TMPDIR
  mkdir -p $TMPDIR
  for clustername in coolstore-a; do
    config="$(oc get -n $clustername secrets -l hive.openshift.io/secret-type=kubeconfig -o jsonpath='{.items[0].data.kubeconfig}' 2>/dev/null)"
    if [ -z "$config" ]; then
      echo "could not retrieve kubeconfig for $clustername"
      exit 1
    fi
    echo -n "$config" | base64 -d > ${TMPDIR}/${clustername}
  done
  cmd="$cmd --insecure-skip-tls-verify --kubeconfig=${TMPDIR}/${clustername}"

  KAFKA="$(get_kafka)"
  if [ -z "$KAFKA" ]; then
    echo "kafka is not installed on coolstore-a"
    rm -f $TMPDIR
    exit 1
  fi
fi

echo "creating order generator job"
$cmd apply -n $PROJ -f ${BASE}/../yaml/order-generator/order-generator-job.yaml
echo "sleeping"
sleep 30
echo "deleting order generator job"
$cmd delete -n $PROJ -f ${BASE}/../yaml/order-generator/order-generator-job.yaml

rm -f $TMPDIR
