#!/bin/bash

cat <<EOF | oc apply -f -
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-gitops-operator
spec: {}
status: {}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-gitops-operator
  namespace: openshift-gitops-operator
spec:
  upgradeStrategy: Default
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/openshift-gitops-operator.openshift-operators: ""
  name: openshift-gitops-operator
  namespace: openshift-gitops-operator
spec:
  channel: latest
  installPlanApproval: Automatic
  name: openshift-gitops-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
EOF

echo -n "waiting for argocd/openshift-gitops to appear..."
until oc get -n openshift-gitops argocd/openshift-gitops > /dev/null 2>&1; do
  echo -n "."
  sleep 5
done
echo "done"

# This is needed because we don't want ArgoCD to overwrite
# app.kubernetes.io/instance (used for the topology view)
oc patch \
  -n openshift-gitops \
  argocd/openshift-gitops \
  -p '{"spec":{"applicationInstanceLabelKey":"argocd.argoproj.io/instance"}}' \
  --type merge
