#!/bin/bash

TMPDIR=/tmp/alertmanagersettings

cd `dirname $0`
BASE=`pwd`
cd - >> /dev/null

source ${BASE}/../config.sh

# setup kubeconfig files for each cluster
rm -rf $TMPDIR
mkdir -p $TMPDIR
for clustername in coolstore-a; do
  config="$(oc get -n $clustername secrets -l hive.openshift.io/secret-type=kubeconfig -o jsonpath='{.items[0].data.kubeconfig}' 2>/dev/null)"
  if [ -z "$config" ]; then
    echo "could not retrieve kubeconfig for $clustername"
    exit 1
  fi
  echo -n "$config" | base64 -d > ${TMPDIR}/${clustername}
done

cmd="oc --insecure-skip-tls-verify --kubeconfig=${TMPDIR}/coolstore-a"

set -e

$cmd get secret/alertmanager-main \
  -n openshift-monitoring \
  -o jsonpath='{.data.alertmanager\.yaml}' \
| \
base64 -d \
| \
sed \
  -e 's/"group_interval".*/"group_interval": "15s"/' \
  -e 's/"group_wait".*/"group_wait": "15s"/' \
> /tmp/alertmanager.yaml

$cmd set data secret/alertmanager-main \
  -n openshift-monitoring \
  --from-file=alertmanager.yaml=/tmp/alertmanager.yaml

rm -f /tmp/alertmanager.yaml

rm -rf $TMPDIR
