#!/bin/bash

cd $(dirname $0)
BASE=$(pwd)
cd - >> /dev/null

source ${BASE}/../config.sh

# check if we have everything deployed on the connected cluster (single
# cluster install)
ROUTE_HOST="$(oc get -n $PROJ route/maildev -o jsonpath='{.spec.host}' 2>/dev/null)"
if [ -n "$ROUTE_HOST" ]; then
  open "http://$ROUTE_HOST"
  exit
fi

ADMIN_PASSWORD="$(oc get -n openshift-gitops secret/openshift-gitops-cluster -o jsonpath='{.data.admin\.password}' | base64 -d)"

if [ -z "$ADMIN_PASSWORD" ]; then
  echo "error: could not get ArgoCD admin password"
  exit 1
fi

ARGOCD_URL="$(oc get -n openshift-gitops route/openshift-gitops-server -o jsonpath='{.spec.host}')"
if [ -z "$ARGOCD_URL" ]; then
  echo "error: could not get ArgoCD API URL"
  exit 1
fi

ARGOCD_URL="https://$ARGOCD_URL"

TOKEN=$(curl -sk $ARGOCD_URL/api/v1/session -d '{"username":"admin","password":"'"$ADMIN_PASSWORD"'"}' | jq -r .token)
if [ -z "$TOKEN" ]; then
  echo "error: could not get ArgoCD token"
  exit 1
fi

MAILDEV=$(curl -sk -H "Authorization: Bearer $TOKEN" $ARGOCD_URL/api/v1/applications/coolstore-a-monitoring/managed-resources | jq -r '.items[] | select (.kind=="Route") | .liveState' | jq -r '.spec.host')
if [ -z "$MAILDEV" ]; then
  echo "error: could not get coolstore-ui host"
  exit 1
fi

open "https://$MAILDEV"
