#!/bin/bash
# Set the contexts for the clusters, login-a, login-b, login-c and login-hub

oc config get-contexts -oname | grep -q ^login-hub && oc config use-context login-hub 

echo Checking the current context is a ACM Hub cluster
if ! oc get project open-cluster-management; then echo "Error: Please log into the ACM hub cluster on host `hostname` and try again!"; exit 1; fi

#HUB_CONTEXT=`oc config current-context`
#oc config use-context $HUB_CONTEXT

oc config rename-context $(oc config current-context) login-hub >/dev/null 2>&1 || true

for c in a b c
do
	oc config use-context login-hub >/dev/null 2>&1

	oc config delete-context login-$c >/dev/null 2>&1 || true

	# Log into the cluster
	oc login --insecure-skip-tls-verify `oc get -n openshift-gitops secret/coolstore-$c-cluster-secret -o jsonpath='{.data.server}' | base64 -d` --token `oc get -n openshift-gitops secret/coolstore-$c-cluster-secret -o jsonpath='{.data.config}' | base64 -d | jq -r '.bearerToken'` >/dev/null 2>&1

	oc config rename-context $(oc config current-context) login-$c || exit 1
done

oc config use-context login-hub

echo "Contexts created:"
oc config get-contexts -oname| grep ^login-

echo Useful commands:
echo oc --context=login-a -n demo get pod 
echo oc --context=login-a -n ves-system get pod 
echo oc --context=login-a -n ves-system logs vp-manager-0
	
