#!/bin/bash -e
# Set the contexts for the clusters, login-a, login-b, login-c and login-hub

echo Checking the current context is a ACM Hub cluster
if ! oc get project open-cluster-management; then echo "Error: Please log into the ACM hub cluster and try again!"; exit 1; fi

#HUB_CONTEXT=`oc config current-context`
#oc config use-context $HUB_CONTEXT

oc config rename-context $(oc config current-context) login-hub || true

for c in a b c
do
	#set -x

	oc config use-context login-hub

	oc config delete-context login-$c 2>/dev/null || true

	# Log into the cluster
	oc login --insecure-skip-tls-verify `oc get -n openshift-gitops secret/coolstore-$c-cluster-secret -o jsonpath='{.data.server}' | base64 -d` --token `oc get -n openshift-gitops secret/coolstore-$c-cluster-secret -o jsonpath='{.data.config}' | base64 -d | jq -r '.bearerToken'`

	oc config rename-context $(oc config current-context) login-$c
done

oc config use-context login-hub

set +x

echo
echo "Contexts created! Success!"
echo Example usage:
echo oc config use-context login-hub
echo oc config use-context login-a
echo or
echo oc --context=login-a -n demo get pod 
	
