#!/bin/bash

TMPDIR=/tmp/consolebanners

cd `dirname $0`
BASE=`pwd`
cd - >> /dev/null

source ${BASE}/../config.sh
source ${BASE}/generate_kubeconfigs

generate_kubeconfigs $TMPDIR


function apply_banner {
  local bannertext="$1"
  local clustername="$2"
  local cmd="oc --insecure-skip-tls-verify"

  if [ -n "$clustername" ]; then
    cmd="$cmd --kubeconfig=${TMPDIR}/${clustername}"
  fi

  cat <<EOF | $cmd apply -f -
apiVersion: console.openshift.io/v1
kind: ConsoleNotification
metadata:
  name: my-banner
spec:
  text: $bannertext
  location: BannerTop
EOF
}

set -e

apply_banner "Hub Cluster"
for clustername in ${CLUSTER_NAMES[@]}; do
  apply_banner "$clustername" "$clustername"
done

rm -rf $TMPDIR
