#!/bin/bash -e
# Check huge pages

for context in login-a login-b login-c
do
	echo ================================

	workers=`oc --context=$context get node --show-labels --no-headers | grep node-role.kubernetes.io/worker= \
		| grep -v -e submariner.io/gateway=true -e node-role.kubernetes.io/master= | awk '{print $1}'`


	echo -e "Verifying for cluster context $context:"

	for w in $workers
	do

		# Run in background
		(
			line="$line$w: `oc --context=$context get node/$w -o jsonpath='{.status.allocatable.hugepages-2Mi}'`"

			echo -e "$context: $line"
		) &
	done
	wait 
done
