#!/bin/bash

cd `dirname $0`
BASE=`pwd`
cd - >> /dev/null

source ${BASE}/../config.sh

function ensure_set {
	local varName="$1"
	if [ -z "${!varName}" ]; then
		echo "$varName is not set"
		exit 1
	fi
}

ensure_set CLUSTER_NAMES

total=${#CLUSTER_NAMES[@]}

echo "we have to wait for $total clusters to be provisioned"

last_count=-1

while true; do
  count=0
  for clustername in ${CLUSTER_NAMES[@]}; do
    installed="$(oc get -n $clustername clusterdeployment/$clustername -o jsonpath='{.spec.installed}' 2>/dev/null)"
    if [ "$installed" = "true" ]; then
      count=$(( count + 1 ))
    fi
  done
  if [ $count -ne $last_count ]; then
    last_count=$count
    echo -n $last_count

  else
    echo -n "."
  fi
  if [ $last_count -ge $total ]; then
    echo
    break
  fi
  sleep 30
done
